### ISSUE TITLE
Label names on the 2D PCA

### ISSUE THREAD

**Issue by YeahThatGuy** [vahaduo/custompca#1]
Hi there @vahaduo ,

I would like to thank you firstly for the work that you are putting into this application and for making it open source for amateur geneticists.

I enjoy using the 2D PCA, but it would be even better if it were possible to get label names on the surface of the PCA. What's happening is that I sometimes happen to use hundreds of samples from one region and for readability's sake, I label them like this "Country_Region:Label_ID" to get the same marker shape and colour for all. 
Thus, in order to see who's who, I need to hover over each marker. Would it be possible to have an option to have those labels burnt in on the PCA?
Something like [this](https://i.imgur.com/APfhLpt.jpg)

Thank you

**Comment by vahaduo** [comment]
Hi @YeahThatGuy !

Thank you for your message!

You can believe it or not, but I haven't seen it earlier today. Incredible timing.
I've learned a lot about Plotly recently when I was preparing the 3D tool and things that I thought were hard to achieve are actually pretty easy to do.

If you want to add a label to individual sample/s just add label@ at the beginning of the name.
If you want to add a label without adding the point (e.g. name for a cluster with averaged coordinates) use labelonly@.

Labels for all groups are added automatically (coordinates are averaged) on a "Group labels" layer.
After reading your message I've added also automatic labels for all samples. They are placed on a hidden "Sample labels" layer (click it in the legend to show them).

I've changed also the export settings. Default export size is now 1600x1200px and there is a second button that allows export of a custom sized image.

I hope you will find it much easier to use this tool now.
